name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        java_version:
          - 8
          - 11
          - 13
        exclude:
          - os: macos-latest
            java_version: 8
          - os: macos-latest
            java_version: 13
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java_version }}

      - if: runner.os == 'Linux'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install sox speech-tools

      - if: runner.os == 'macOS'
        run: brew install speech-tools

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --warning-mode all
